defmodule GroceryPlanner.Repo.Migrations.SkilletThemes do
  @moduledoc """
  Replaces the 12 stock daisyUI themes with the 4 Skillet themes
  (fairway / orchard / marble / dark) and migrates stored preferences:

  - dark-leaning themes (synthwave, dracula, business, luxury, sunset) → "dark"
  - everything else (light, cupcake, bumblebee, retro, cyberpunk, nord) → "fairway"
  - "dark" stays "dark"

  Default change autogenerated with `mix ash_postgres.generate_migrations`;
  data migration added by hand.
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :theme, :text, default: "fairway"
    end

    execute """
    UPDATE users
    SET theme = 'dark'
    WHERE theme IN ('synthwave', 'dracula', 'business', 'luxury', 'sunset')
    """

    execute """
    UPDATE users
    SET theme = 'fairway'
    WHERE theme NOT IN ('fairway', 'orchard', 'marble', 'dark')
    """
  end

  def down do
    alter table(:users) do
      modify :theme, :text, default: "light"
    end

    # Skillet names are unknown to the old validator; map to the old defaults.
    execute """
    UPDATE users
    SET theme = 'light'
    WHERE theme IN ('fairway', 'orchard', 'marble')
    """
  end
end
