defmodule GroceryPlanner.Repo.Migrations.VzcMealPlanSlotUniqueness do
  @moduledoc """
  Enforces one live meal per (account_id, scheduled_date, meal_type) slot
  (grocery_planner-vzc).

  Existing duplicate live rows must be resolved before the partial unique index
  can build. We keep the newest row per slot (by created_at, then id) and
  soft-delete the rest. This is lossy when duplicates hold *different* recipes —
  the older recipe is soft-deleted, not merged — which is the accepted call for
  clearing accumulated orphan rows. Soft-deleted rows are left in place on
  rollback (the dedup does not reverse).

  Index generated by `mix ash_postgres.generate_migrations`; the dedup was
  added by hand and must run before the index is created.
  """

  use Ecto.Migration

  def up do
    execute("""
    UPDATE meal_plans m
    SET deleted_at = NOW()
    WHERE m.deleted_at IS NULL
      AND EXISTS (
        SELECT 1
        FROM meal_plans keep
        WHERE keep.deleted_at IS NULL
          AND keep.account_id = m.account_id
          AND keep.scheduled_date = m.scheduled_date
          AND keep.meal_type = m.meal_type
          AND (keep.created_at > m.created_at
               OR (keep.created_at = m.created_at AND keep.id > m.id))
      )
    """)

    create unique_index(:meal_plans, [:account_id, :scheduled_date, :meal_type],
             name: "meal_plans_unique_slot_per_account_index",
             where: "(deleted_at IS NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:meal_plans, [:account_id, :scheduled_date, :meal_type],
                     name: "meal_plans_unique_slot_per_account_index"
                   )
  end
end
