defmodule GroceryPlanner.Repo.Migrations.Ai006Arc2StageConditionPipeline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:receipts) do
      remove :error_message
      remove :status
      add :stage, :text, null: false, default: "pending"
      add :condition, :text, null: false, default: "ok"
      add :failure_reason, :text
      add :raw_extraction, :map
    end

    alter table(:receipt_items) do
      add :line_no, :bigint
    end

    create index(:receipt_items, [:account_id, :receipt_id, :line_no],
             name: "receipt_items_receipt_id_line_no_index",
             unique: true,
             where: "line_no IS NOT NULL"
           )
  end

  def down do
    drop_if_exists index(:receipt_items, [:account_id, :receipt_id, :line_no],
                     name: "receipt_items_receipt_id_line_no_index"
                   )

    alter table(:receipt_items) do
      remove :line_no
    end

    alter table(:receipts) do
      remove :raw_extraction
      remove :failure_reason
      remove :condition
      remove :stage
      add :status, :text, null: false, default: "pending"
      add :error_message, :text
    end
  end
end
